name: SalesStore - CD Pipeline

on:
  #Se ejecutará inemdiatamente después de que el Pipeline de CI termine.
  workflow_run:
    workflows: ["SalesStore - CI Pipeline"]
    types:
      - completed

# Definimos variables globales para el pipeline
env:
  APP_NAME_CUSTOM: "sales-api-backend-${{ vars.ENVIRONMENT }}" # <-- AQUÍ CAMBIAS EL NOMBRE PERSONALIZADO CUANDO QUIERAS

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: development    #Es el environment que creamos en nuestro Github (almacena nuestras variables y/o secretos)
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # 1. Conectarse al clúster de AKS usando Azure CLI
      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      
      # 2. Crear o actualizar los secretos dentro de Kubernetes de forma segura
      # Vamos a inyectarle los valores proveniente de los secretos de Github a las llaves (keys) del archivo k8s/deployment.yml
      - name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic backend-secrets \
            --from-literal=db-connection-string="${{ secrets.DB_CONNECTION_STRING }}" \
            --from-literal=storage-connection-string="${{ secrets.STORAGE_CONNECTION_STRING }}" \
            --from-literal=jwt-secret="${{ secrets.JWT_SECRET }}" \
            --dry-run=client -o yaml | kubectl apply -f -
      
      # 3. Personalizar dinámicamente el Manifiesto de K8s (Nombre de la App e Imagen)
      - name: Customize K8s Manifest
        run: |
          # Reemplaza todos los marcadores __APP_NAME__ con el nombre personalizado
          sed -i "s|__APP_NAME__|${{ env.APP_NAME_CUSTOM }}|g" k8s/deployment.yml
          
          # Reemplaza el marcador de la imagen con el servidor ACR y el SHA del commit
          sed -i 's|__IMAGE_PLACEHOLDER__|${{ secrets.ACR_LOGIN_SERVER }}/sales-api:${{ github.event.workflow_run.head_sha }}|g' k8s/deployment.yml
      
      # 4. Desplegar en AKS con el archivo ya personalizado
      - name: Deploy to AKS Cluster
        run: |
          kubectl apply -f k8s/deployment.yml