name: SalesStore - CI Pipeline

on:
  push:
    branches: [ "main" ] # Se dispara al fusionar a main

# Definimos variables globales para el pipeline
env:
  APP_NAME_CUSTOM: "sales-api-backend-${{ vars.ENV }}"
  AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  # ==========================================
  # FASE 1: INTEGRACIÓN CONTINUA (CI)
  # ==========================================
  build-and-push:
    name: "[CI] Build & Push"
    environment: development
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # El JSON del Service Principal
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      
      # Aseguramos el contexto del CLI en el CD
      - name: Set Azure Subscription Context
        run: |
          az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
      
      # Generaremos una build / artefacto con 1 tag: el SHA-ID (commit)
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/sales-api:${{ github.sha }} -f src/ApiSolutionTestVentas.Api/Dockerfile .
          
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/sales-api:${{ github.sha }}
  
  # ==========================================
  # FASE 2: DESPLIEGUE CONTINUO (CD)
  # ==========================================
  deploy-to-dev:
    name: "[CD] Deploy to AKS"
    needs: build-and-push       #Asegura que el CD espere a que termine el CI con éxito
    environment: development
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Estandarizado: Login con suscripción explícita
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      # Aseguramos el contexto del CLI en el CD
      - name: Set Azure Subscription Context
        run: |
          az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

      # Conectarse al clúster de AKS usando Azure CLI
      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # rear o actualizar los secretos dentro de Kubernetes de forma segura
      - name: "Create Kubernetes Secrets"
        run: |
          kubectl create secret generic backend-secrets \
            --from-literal=db-connection-string="${{ secrets.DB_CONNECTION_STRING }}" \
            --from-literal=storage-connection-string="${{ secrets.STORAGE_CONNECTION_STRING }}" \
            --from-literal=jwt-secret="${{ secrets.JWT_SECRET }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      # 3. Personalizar dinámicamente el Manifiesto de K8s (Nombre de la App e Imagen)
      - name: "Customize K8s Manifest"
        run: |
          # Reemplaza todos los marcadores __APP_NAME__ con el nombre personalizado
          sed -i "s|__APP_NAME__|${{ env.APP_NAME_CUSTOM }}|g" k8s/deployment.yml

          # Reemplaza el marcador de la imagen con el servidor ACR y el SHA del commit
          sed -i 's|__IMAGE_PLACEHOLDER__|${{ secrets.ACR_LOGIN_SERVER }}/sales-api:${{ github.sha }}|g' k8s/deployment.yml

      # 4. Desplegar en AKS con el archivo ya personalizado
      - name: "Deploy to AKS Cluster"
        run: |
          kubectl apply -f k8s/deployment.yml